name: Compile and Deploy Resume

on:
  push:
    branches:
      - ci

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Build Docker image
      #   run: docker build -t resume-builder .

      # - name: Run Docker container to generate resume
      #   run: |
      #     chmod +x ./compile_resume.sh
      #     docker run -v .:/usr/local/resume resume-builder

      - name: Clone target repository
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/personal-repos-mazen/Portfolio-Website.git Portfolio-Website

      - name: Copy generated resume to target repository path
        run: |
          mkdir out
          echo pdf > ./out/resume.pdf
          cp ./out/resume.pdf Portfolio-Website/public/resume.pdf

      - name: Commit and push to target repository
        run: |
          cd Portfolio-Website
          git config --global user.email "mazenbahgat@outlook.com"
          git config --global user.name "mbahgatTech"
          git add public/resume.pdf
          git commit -m "Update resume"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/personal-repos-mazen/Portfolio-Website.git
          git push
